### ISSUE TITLE
Feature Request to add additional detection bypass method

### ISSUE THREAD

**Issue by clr2of8** [curi0usJack/luckystrike#16]
If you try to send the output of this tool (XLS file with powershell empire payload) via gmail, Google detects the virus.  Can you implement this bypass technique, which solves this problem http://www.blackhillsinfosec.com/?p=4679

Something like:
c = "poW" & Chr(101)
c = c + Chr(114) & Chr(83) . . . .

**Comment by curi0usJack** [comment]
Hi Carrie,

For sure. I'm working on a few more bypass techniques. Right now luckystrike doesn't do any processing of the payload itself (something else I'm working on). You can, however, add your own obfuscation when you insert the payload. Luckystrike will prepend and append double quotes, so enter it like so:

![image](https://cloud.githubusercontent.com/assets/5608516/21110237/04ae999e-c062-11e6-952f-ee3f88825b52.png)

That way it's at least stored with the obfuscation in the database. Hope that helps until I can get something permanent built.

**Comment by clr2of8** [comment]
Sweet, thanks.

**Comment by curi0usJack** [comment]
fyi, going to be pushing luckystrike 2.0 here soon. Powershell payload obfuscation is included. :-)
