### ISSUE TITLE
Get error when open .xls with luckstrike

### ISSUE THREAD

**Issue by ztencmcp** [curi0usJack/luckystrike#27]
Hello,

When i finished all steps and got malicious xls file, I found that the macro threw a error:"Compile error---sub procedure or function not defined". What's going on here? Thank you!

**Comment by curi0usJack** [comment]
1) What payload type & infection type did you choose?
2) Can you post a screenshot of the macro code & error please?

**Comment by ztencmcp** [comment]
Hello,

Thanks for responding, the payload is .ps1 , the infection type is default. I didn't set it. Here's screenshot:
![20170527113145](https://cloud.githubusercontent.com/assets/22705390/26517717/572caade-42d1-11e7-969f-62738dfb3594.png)

**Comment by ztencmcp** [comment]
any update? Bro.

**Comment by curi0usJack** [comment]
Ah, I see it. You found a bug. Delete the line I've highlighted in the screenshot below and you should be good to go. Fixed in the next release:

![image](https://cloud.githubusercontent.com/assets/5608516/26695489/ac5b9c38-46d0-11e7-8475-f4de13439dcc.png)

**Comment by curi0usJack** [comment]
any update bro? ;-)
