### ISSUE TITLE
seg faults

### ISSUE THREAD

**Issue by ccammilleri** [curi0usJack/luckystrike#28]
works than seg faults when i press the W key. my computer does powershell very well. can you halp me? would be cool if it could do the auto hamburger attack.

If 7-11 is open 24 hours a day, 365 days a year, why are there locks on the doors?

**Comment by Snizz** [comment]
![download](https://cloud.githubusercontent.com/assets/11081273/26683305/f7557100-46a8-11e7-9cda-244fef2f468e.jpg)

**Comment by curi0usJack** [comment]
Updating to include hamburger attack...

**Comment by curi0usJack** [comment]
har
