### ISSUE TITLE
Crash when using reflectivePE

### ISSUE THREAD

**Issue by rami418** [curi0usJack/luckystrike#30]
Hi,

LuckyStrike crash when using an executable with reflectivePE infection. having the attached issue. Working on Win7 32bits.

![bug](https://user-images.githubusercontent.com/26768345/28367287-94ad7fee-6c90-11e7-92dc-d2d59d4b0911.png)

Any idea ?

Thanks

**Comment by curi0usJack** [comment]
Have you tested the exe with Invoke-ReflectedPEInjection to make sure it works?

**Comment by curi0usJack** [comment]
No comment from OP
