### ISSUE TITLE
obfuscation module

### ISSUE THREAD

**Issue by bkr32** [curi0usJack/luckystrike#32]
Hi, on launch the following error is given `[!] - Module Invoke-Obfuscation not installed. Obfuscation options will not be available.` 
which invoke-Obfuscation module should be used and how is it to be installed?

thanks

**Comment by curi0usJack** [comment]
In order to use the infection types that require obfuscation, a powershell module called Invoke-Obfuscation must be installed. The module code is here: https://github.com/danielbohannon/Invoke-Obfuscation.

When it comes to installing powershell modules, Google is your friend. :-)

**Comment by bkr32** [comment]
thanks for the link :D
