### ISSUE TITLE
module invoke-obfuscation missing

### ISSUE THREAD

**Issue by johnjohnsp1** [curi0usJack/luckystrike#33]
Hello, I'm getting this message once i install and run lucky strike module.
As attachment the log file and the screenshot.

are you able to tell me how to properly install invoke-obusfcation by any chance ? I did git clone that repo and imported module but seems not working like this.

thanks
<img width="854" alt="luckystrike_module_missing" src="https://user-images.githubusercontent.com/1888855/29001142-b998d206-7a80-11e7-9710-13e202a7204b.png">
[ls-debug-08062017082020.txt](https://github.com/curi0usJack/luckystrike/files/1202918/ls-debug-08062017082020.txt)
<img width="854" alt="luckystrike_module_missing" src="https://user-images.githubusercontent.com/1888855/29001148-eeaa904c-7a80-11e7-81b4-34609d39beb2.png">

**Comment by curi0usJack** [comment]
New powershell modules go into your PS profile/Modules directory.

Google is your friend here: https://msdn.microsoft.com/en-us/library/dd878350(v=vs.85).aspx

**Comment by johnjohnsp1** [comment]
Thanks for the reply,

	totally forgot about profile folder, my bad.

Confirm is no longer complain about obfuscation missing:

PS C:\Users\test\Documents\WindowsPowerShell\Modules\Invoke-Obfuscation> cd C:\temp\luckystrike\
PS C:\temp\luckystrike> ls


    Directory: C:\temp\luckystrike


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       06/08/2017     11:49          51200 ls.db
-a----       06/08/2017     11:48         258096 luckystrike.ps1


PS C:\temp\luckystrike> .\luckystrike.ps1

    __               __            _____ __       _ __
   / /   __  _______/ /____  __   / ___// /______(_) /_____
  / /   / / / / ___/ //_/ / / /   \__ \/ __/ ___/ / //_/ _ \
 / /___/ /_/ / /__/ ,< / /_/ /   ___/ / /_/ /  / / ,< /  __/
/_____/\__,_/\___/_/|_|\__, /   /____/\__/_/  /_/_/|_|\___/
                      /____/

                ALL YOUR PAIN IN ONE MACRO.

                  2.0 - @curi0usJack


============= Main Menu ================

        1)  Payload Options
        2)  Catalog Options
        3)  File Options
        4)  Encode a PowerShell Command
        99) Exit


Luca Grembo
Piazza AldoMoro 4 Scala 8
20021-Bollate
Milano (Italia)
+39 3930413941
luca.grembo@gmail.com
skype:lucagrembo

**Comment by salamohamad** [comment]
I cannot get my head around this issues, could you please tell me how you didi it

**Comment by curi0usJack** [comment]
@salamohamad helpful Google search terms: "Installing powershell modules"

**Comment by salamohamad** [comment]
Thanks, I did and it was only like misplacement of the folder.
 If you run into this problem. download the Invoke-Obfuscation from git change the folders name to Invoke-Obfuscation instead of Invoke-Obfuscation-master , install it and copy Invoke-Obfuscation folder to the modules folder in the Powershell file in the sys. it should work 
it should work
