### ISSUE TITLE
Error occurred creating document

### ISSUE THREAD

**Issue by bilimaster** [curi0usJack/luckystrike#38]
in Windows 10 and Windows 8.1 i have the same probleme to generate office doc with luckystrike 2.0.
 please find attached document log.
 with my best thinks
[ls-debug-08222017163953.txt](https://github.com/curi0usJack/luckystrike/files/1245360/ls-debug-08222017163953.txt)

**Comment by curi0usJack** [comment]
![image](https://user-images.githubusercontent.com/5608516/29633378-b5ac6476-880b-11e7-9f70-c7e5c2368d37.png)

Mind translating that to English please?

**Comment by bilimaster** [comment]
Think you  for tour fast reply.
Sorry m'y Windows is in franch language.
Microsoft excel can not access c: \ windows \ system32 \ luckystrike \ payloads. Several possible reasons: 
The file name or path does not exist. 
This file is currently being used by another program. 
The workbook you are trying to save has the same name as a currently open workbook.
Thon''sur

**Comment by bilimaster** [comment]
Think you for your fast reply.
Sorry m'y Windows is in franch language.
Microsoft excel can not access c: \ windows \ system32 \ luckystrike \ payloads. Several possible reasons:
The file name or path does not exist.
This file is currently being used by another program.
The workbook you are trying to save has the same name as a currently open workbook.
Think's
