### ISSUE TITLE
exe payload not working

### ISSUE THREAD

**Issue by ankushgoel27** [curi0usJack/luckystrike#39]
hi,

I add an exe payload and create an excel file. However i get an error saying file not found. The file is still on my computer and the path is correct. No errors are generated by the luckystrike script. Its when i run the macro code, that i get this error. I tried both certutil and save to disk method.

**Comment by curi0usJack** [comment]
Run luckystrike with the -Debug flag and post the debug log file here please.

**Comment by curi0usJack** [comment]
Closed. No response from OP.
